### ISSUE TITLE
Shouldn't use 'crossorigin="false"'

### ISSUE THREAD

**Issue by SukkaW** [giuem/hexo-filter-crossorigin#7]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes):

> An invalid keyword and an empty string will be handled as the `anonymous` keyword.

**Comment by giuem** [comment]
https://github.com/giuem/hexo-filter-crossorigin/blob/master/src/appendAttr.ts#L44

When setting crossorigin to false, it will skip processing.

**Comment by SukkaW** [comment]
Ah, fine!
